### ISSUE TITLE
SMD's

### ISSUE THREAD

**Issue by daincrawford** [g2maurer/CUBOTino2#1]
I there any chance we could get a list of the LEDs, resistors and small surface mount capacitors. Adafruit has the large capacitors, but none of the surface mount. I have looked at DigiKey and Mouser, but I have no idea what I actually need. I was able to get your boards from PCBway. Thank you very much for making them available and I am really looking forward to completing this project. 
I have all of the rest of the parts either ordered or already received.  Again thank you for your fine work.

**Comment by g2maurer** [comment]
I will send you a list.

**Comment by g2maurer** [comment]
I purchased the resistors, capacitors and LEDs on Amazon. They come as assorted kits. Here are some Amazon links to what I purchased:

Resistors:  https://www.amazon.com/gp/product/B09538ZBCR/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1
Capacitors:  https://www.amazon.com/gp/product/B06XD3K15S/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
LEDs:  https://www.amazon.com/gp/product/B01CUGA8JO/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1
Note: these are for is 0805 size components.

The two components that are 1206 size are C5 and D2 (2.2uF capacitor and LED).
Here is the links to the 1206 size components:
LED:  https://www.amazon.com/gp/product/B01CUGAFEC/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1
Capacitor:  https://www.amazon.com/gp/product/B06XDHC93D/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

I have in the past put the 0805 components on the 1206 pads.

I have purchased individual components from Mouser but I found it cheaper to just buy the kits from Amazon.
The individual components are typically cheaper from Mouser but the shipping results in them being just as costly as Amazon.

**Comment by g2maurer** [comment]
BTW: The BOM is in the file PCB/CUBOTino2.csv

**Comment by daincrawford** [comment]
Gerald,
Thank you so much for the quick thorough response. My order is already
placed.
These were the last parts that I needed tied down.
I will let you know how this project turns out.
Dain

**Comment by g2maurer** [comment]
I purchased the surface mount components on Amazon. The SMD sizes I used
are 0805 and 1206.
The BOM lists the size of each component.
Here are some links to the parts I purchased on Amazon.

https://www.amazon.com/gp/product/B06XD3K15S/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
     Capacitors  size  0805

https://www.amazon.com/gp/product/B06XDHC93D/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
    Capacitors size 1206

https://www.amazon.com/gp/product/B09538ZBCR/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1
      Resistors size 0805

https://www.amazon.com/gp/product/B01CUGA8JO/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1
     LEDs size 0805

https://www.amazon.com/gp/product/B01CUGAFEC/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1
     LEDs  size 1206
